import React from 'react';

import LandingHeader from '../../components/LandingHeader';

import './styles.css';

export default function Query() {
   return (
      <div id="queryContainer" className="firstContainer container">
         <header>
            <LandingHeader />
         </header>
         <main>
            {/* Não contém className container pois o display flex causa um bug na expansão das tabelas */}
            <div id="schemaContainer">
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
               <table>
                  <caption>Estado</caption>
                  <tbody>
                     <tr>
                        <td>Nome</td>
                        <td>Sigla</td>
                        <td>UF</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                        <td>Extensão</td>
                     </tr>
                  </tbody>
               </table>
            </div>

            <textarea name="query" id="queryText" placeholder="SELECT * FROM ..."></textarea>
         </main>
      </div>
   );
}
