version: '3.5'
services:
   backend:
      build: './backend'
      image: geosql/backend:${VERSION}
      args:
         - NODE_OPTIONS="--max-old-space-size=8192"
   frontend:
      build:
         context: './frontend'
         args:
            #          - NODE_ENV=production
            - PUBLIC_URL=http://greenwich.lbd.dcc.ufmg.br
            - REACT_APP_BASE_URL=/
            - REACT_APP_API_URL=/api
      image: geosql/frontend:${VERSION}
